### ISSUE TITLE
build 시 checkstyle이 An unexpected error occurred configuring and executing Checkstyle 에러를 뱉음

### ISSUE THREAD

**Issue by park-se-jun** [prgrms-web-devcourse/Team-6Jeans-Hype-BE#45]

**Comment by park-se-jun** [comment]
`gradlew checkstyleMain --stacktrace` 결과 checkstyle의 버전이 낮아 record를 읽지 못하는 문제였음(java 17 지원 x)

```
Caused by: G:\IdeaProjects\Team-06-Final-BE\src\main\java\com\example\demo\common\ApiResponse.java:7:8: unexpected token: record
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:584)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)
	... 47 more
```
![image](https://user-images.githubusercontent.com/28258648/220153936-b8790044-60a9-438c-afc9-2e5aaf3babaf.png)

checkstyle 버전 업을 통해 해결
